import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');
const TOP_PADDING = Platform.OS === 'ios' ? 44 : 0;
const BOTTOM_PADDING = Platform.OS === 'ios' ? 34 : 0;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fafafa',
    paddingTop: TOP_PADDING,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
  },
  shopHeader: {
    width: '100%',
    height: height * 0.25,
    backgroundColor: '#000',
  },
  shopImage: {
    width: '100%',
    height: '100%',
    opacity: 0.9,
  },
  shopInfo: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    paddingBottom: 20,
    background: 'linear-gradient(180deg, rgba(0,0,0,0) 0%, rgba(0,0,0,0.8) 100%)',
  },
  shopName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  shopDescription: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    lineHeight: 18,
    letterSpacing: 0.2,
  },
  categorySection: {
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 8,
    backgroundColor: '#fff',
  },
  categoryTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
    color: '#1c1c1c',
    letterSpacing: 0.2,
  },
  menuItem: {
    marginBottom: 16,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  inactiveItem: {
    opacity: 0.7,
  },
  menuItemImage: {
    width: width * 0.22,
    height: width * 0.22,
    borderRadius: 12,
    backgroundColor: '#f5f5f5',
  },
  menuItemInfo: {
    flex: 1,
    marginLeft: 14,
    paddingRight: 8,
  },
  menuItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  itemName: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1c1c1c',
    flex: 1,
    marginRight: 8,
    letterSpacing: 0.2,
  },
  menuItemDescription: {
    color: '#696969',
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
    letterSpacing: 0.1,
  },
  menuItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  price: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1c1c1c',
  },
  inactivePrice: {
    textDecorationLine: 'line-through',
    color: '#999',
  },
  addButton: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 0.8,
    borderColor: '#60b246',
  },
  inactiveButton: {
    backgroundColor: '#f5f5f5',
    borderColor: '#e0e0e0',
  },
  addButtonText: {
    color: '#60b246',
    fontWeight: '500',
    fontSize: 13,
    letterSpacing: 0.2,
  },
  inactiveButtonText: {
    color: '#999',
  },
  dietTypeBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 4,
  },
  dietTypeText: {
    fontSize: 10,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: height * 0.85,
    overflow: 'hidden',
  },
  modalClose: {
    position: 'absolute',
    right: 20,
    top: 20,
    zIndex: 2,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  modalImage: {
    width: '100%',
    height: height * 0.3,
  },
  modalInfo: {
    padding: 20,
  },
  modalItemName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1c1c1c',
    marginBottom: 6,
    letterSpacing: 0.2,
  },
  modalDescription: {
    marginTop: 10,
    color: '#696969',
    lineHeight: 20,
    fontSize: 14,
    letterSpacing: 0.1,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 0.5,
    borderTopColor: '#eee',
  },
  modalPrice: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1c1c1c',
    letterSpacing: 0.2,
  },
  modalAddButton: {
    backgroundColor: '#60b246',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    minWidth: 110,
    alignItems: 'center',
  },
  modalAddButtonText: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0.2,
  },
  cartButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? TOP_PADDING + 8 : 16,
    right: 16,
    backgroundColor: '#fff',
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  badge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#60b246',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  badgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '500',
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: BOTTOM_PADDING + 16,
  },
  divider: {
    height: 1,
    backgroundColor: '#f5f5f5',
    marginVertical: 8,
  }
});